config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories
  resources :categories, except: [:destroy]
end

app/models/article.rb
# frozen_string_literal: true

# app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 6 }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# app/controller/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]
  # GET /articles or /articles.json
  def index
    @articles = Article.order(updated_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, category_ids: [])
  end

  def require_same_user
    return if current_user == @article.user || current_user.admin?

    flash[:alert] = 'You can only edit or delete your own article!'
    redirect_to @article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <!--<div class="row justify-content-center">
    <%= link_to 'New Article', new_article_path, class: 'btn btn-primary btn-lg shadow rounded mb-4' %>
  </div>-->
  <% resource.each do |article| %>
    <div class="row justify-content-center">
      <div class="col-8 mb-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, article.user, class: 'text-secondary' %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article, class: 'text-success' %></h5>
            <p class="card-text"><%= truncate(article.body, length: 100) %></p>
            <%= link_to 'View', article, class: "btn btn-outline-success rounded-pill mt-1" %>
            <% if logged_in? && (article.user == current_user or current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info rounded-pill mt-1" %>
              <%= link_to 'Destroy', article, class: "btn btn-outline-danger rounded-pill mt-1", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <% if article.created_at == article.updated_at %>
              <small><%= "Created #{time_ago_in_words(article.created_at)} ago." %></small>
            <% else %>
              <small><%= "Created #{time_ago_in_words(article.created_at)} ago, Updated #{time_ago_in_words(article.updated_at)} ago" %></small>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', resource: @article %>
      <%= form_with(model: article, class: 'shadow p-3 mb-3 bg-white rounded-lg') do |form| %>
        <div class="form-group row mt-3">
          <%= form.label :title, class: 'col-2 col-form-label' %>
          <div class="col-10">
            <%= form.text_field :title, class: 'form-control shadow rounded-lg', placeholder: 'Title of article' %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :body, class: 'col-2 col-form-label' %>
          <div class="col-10">
            <%= form.text_area :body, rows: 10, class: 'form-control shadow rounded-lg', placeholder: 'Body of article' %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :category, class: 'col-2 col-form-label' %>
          <div class="col-10">
            <%= form.collection_select(:category_ids, Category.all, :id, :name, 
            { prompt: 'Make your selection from the list below (can be empty)' }, { multiple: true, size: 3, class: 'custom-select shadow rounded' }) %>
          </div>
        </div>        
        <div class="form-group row justify-content-center">
          <%= link_to 'Cancel', articles_path, class: 'btn btn-danger btn-lg rounded-pill text-center' %>
          <%= form.submit class: 'btn btn-primary btn-lg rounded-pill ml-1' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit articles</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4">Articles</h1>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article', resource: @articles %>
<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new articles</h1>
  
  <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mb-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if @article.user %>
            by <%= link_to @article.user.username, @article.user, class: 'text-secondary' %>
               <%= link_to gravatar_for(@article.user, option: 100), user_path(@article.user) %>
               <% if @article.categories.any? %>
                <div class="mt-2"><%= render @article.categories %></div>
               <% end %>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.body) %></div>
          <%= link_to 'Back', articles_path, class: 'btn btn-outline-success text-center rounded-pill ml-1' %>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info rounded-pill" %>
            <%= link_to 'Destroy', @article, class: "btn btn-outline-danger rounded-pill", method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <% if @article.created_at == @article.updated_at %>
            <small><%= "Created #{time_ago_in_words(@article.created_at)} ago." %></small>
          <% else %>
            <small><%= "Created #{time_ago_in_words(@article.created_at)} ago, Updated #{time_ago_in_words(@article.updated_at)} ago" %></small>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>