config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories
  resources :categories, except: [:destroy]
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.order(updated_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category name updated successfully'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admin can perform that action'
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: 'badge badge-pill badge-info mr-1' %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', resource: @category %>
      <%= form_with(model: @category, class: 'shadow p-3 mb-3 bg-white rounded-lg') do |form| %>
        <div class="form-group row mt-3">
          <%= form.label :name, 'Category Name', class: 'col-2 col-form-label' %>
          <div class="col-10">
            <%= form.text_field :name, class: 'form-control shadow rounded-lg', placeholder: 'Enter a category name' %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= link_to 'Cancel', categories_path, class: 'btn btn-danger btn-lg rounded-pill text-center' %>
          <%= form.submit class: 'btn btn-primary btn-lg rounded-pill ml-1' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit Category</h1>
  
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>

<div class="apple_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-center">
      <div class="col-4 mb-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: 'text-success' %></h5>
            <small class="card-text font-size-2"><%= pluralize(category.articles.count, 'article') %></small>
            <% if logged_in? && current_user.admin? %>
              <div class="mt-2">
                <%= link_to 'Edit', edit_category_path(category), class: "btn btn-outline-info rounded-pill" %>
                <%= link_to 'Destroy', category, class: "btn btn-outline-danger rounded-pill", method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <% if category.created_at == category.updated_at %>
              <small><%= "Created #{time_ago_in_words(category.created_at)} ago." %></small>
            <% else %>
              <small><%= "Created #{time_ago_in_words(category.created_at)} ago, Updated #{time_ago_in_words(category.updated_at)} ago" %></small>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="apple_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new category</h1>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Category: <%=@category.name %></h1>
</div>

  <div class="text-center mt-4">
    <% if logged_in? and current_user.admin? %>
      <%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-outline-info rounded-pill" %>
    <% end %>
  </div>
  <h3 class="text-center mt-4">Articles</h3>
  <div class="apple_pagination mb-4">
    <%= will_paginate @category_articles, :container => false %>
  </div>
  <% if @category_articles.present? %>
    <%= render 'articles/article', resource: @category_articles %>
    <div class="apple_pagination mb-4">
      <%= will_paginate @category_articles, :container => false %>
    </div>
  <% else %>
    <h5 class="text-center text-secondary mt-4">This category isn't have an article!</h5>
  <% end %>