config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]

  # Sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Categories
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to 'Andrian Rizki', 'https://instagram.com/andrian_rized', class: 'text-white' %></small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'BADAMI', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'List articles', articles_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Create new article', new_article_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <% if type == 'notice' %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>      
    <% else %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>      
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'BADAMI', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon navbar-dark"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'List articles', articles_path, class: 'dropdown-item' %>
          <% if logged_in? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create new article', new_article_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'List categories', categories_path, class: 'dropdown-item' %>
          <% if logged_in? && current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create new category', new_category_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= current_user.admin? ? "👮🏻 - #{current_user.username.capitalize}" : current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View your profile', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Edit your profile', edit_user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>            
            <%= link_to "Delete profile", user_path(current_user), class: 'dropdown-item text-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', logout_path, class: 'dropdown-item text-secondary', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li >
        <li class="nav-item">
          <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
        </li >
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control rounded-pill mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success rounded-pill my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Badami</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>